authapp/urls.py
from authapp.apps import AuthappConfig
from django.urls import path
from authapp.views import CustomLoginView, RegisterView, CustomLogoutView, EditView

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit/', EditView.as_view(), name='edit'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', RedirectView.as_view(url='mainapp/')),
    path ('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path ('authapp/', include('authapp.urls', namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social'))

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from mainapp.models import NULLABLE

class User(AbstractUser):
    email = models.EmailField(blank=True, verbose_name=_('email'), unique=True)
    age = models.PositiveSmallIntegerField(verbose_name=_('age'), **NULLABLE)
    avatar = models.ImageField(upload_to='users', **NULLABLE, verbose_name=_('avatar'))

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

authapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'age',
            'avatar'
        )

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 18:
            raise ValidationError('Вы слишком молоды для этого сайта')
        return age

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'age',
            'avatar'
        )

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 18:
            raise ValidationError('Вы слишком молоды для этого сайта')
        return age

authapp/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView

from authapp.forms import CustomUserCreationForm, CustomUserChangeForm
from authapp.models import User


class CustomLoginView(LoginView):
    template_name = 'authapp/login.html'
    extra_context = {
        'title': 'Вход пользователя'
    }


class RegisterView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('mainapp:index')



class CustomLogoutView(TemplateView):
    pass

class EditView(UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = 'authapp/edit.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('authapp:edit', args=[self.request.user.pk])

authapp/templates/authapp/base.html
{% load static %}
<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <title>Welcome to GeekLab!</title>
</head>

<body>

{% include 'authapp/includes/inc_messages.html' %}



<div class="row justify-content-around align-items-center" style="height: 100vh; margin: 0px">
  <div class="text-center">
    <p>
      <a href="/"><img src="{% static 'img/logo.png' %}" alt=""></a>
    </p>
    <h2>{{ title }}</h2>
      {% block content %}
      {% endblock %}
      </p>
      <h4>Вход через социальные сети</h4>
      <p>
      <div class="btn-group btn-block" role="group">
          <a class="btn btn-primary" href="#" role="button"><i class="fab fa-vk"></i></a>
          <a class="btn btn-primary" href="{% url 'social:begin' 'github' %}" role="button"><i class="fab fa-github"></i></a>
          <a class="btn btn-primary" href="#" role="button"><i class="fab fa-facebook"></i></a>
      </div>
      </p>

  </div>
</div>


    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- ChartJs -->
    <script src="{% static 'js/Chart.min.js' %}"></script>

    <!-- FontAwesome -->
    <script src="{% static 'js/fontawesome.all.min.js' %}"></script>

{% block js %}

{% endblock %}

</body>

</html>

authapp/templates/authapp/edit.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_tags i18n %}
{% block content %}
    <form class="col-6 m-auto pt-5 pb-5" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <p>
            <button type="submit" class="btn btn-primary btn-block">
                {% translate 'save' %}
            </button>
        </p>
    </form>

{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            {% if messages %}
                // Toasts
                $(".toast").toast({delay: 5000});
                $(".toast").toast("show");
            {% endif %}
        });
    </script>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>
        <input id="id_username" class="form-control" type="text" name="username" placeholder="Имя пользователя"
               required="" autofocus="">
    </p>
    <p>
        <input id="id_password" class="form-control" type="password" name="password" placeholder="Пароль" required="">
    </p>
    <p>
        <button type="submit" class="btn btn-primary btn-block">Войти</button>
    </p>
</form>
<div class="row justify-content-between">
    <div class="col">
        <a href="{% url 'authapp:register' %}"><small>Регистрация</small></a>
    </div>
    <div class="col">
        <a href="#"><small>Забыли пароль?</small></a>
    </div>
</div>

{% endblock %}

authapp/templates/authapp/user_form.html
{% extends 'authapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <p>
            <button type="submit" class="btn btn-primary btn-block">
                Зарегистрироваться
            </button>
        </p>
    </form>
    <p>
    <div class="row justify-content-between">
        <div class="col">
            <a href="{% url 'authapp:login' %}"><small>Войти</small></a>
        </div>
        <div class="col">
            <a href="#"><small>Забыли пароль?</small></a>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            {% if messages %}
                // Toasts
                $(".toast").toast({delay: 5000});
                $(".toast").toast("show");
            {% endif %}
        });
    </script>
{% endblock %}